---
output: md_document
bibliography: "bibliography/references.bib"
---

# Non-parametric Bounds in Two-Sample Summary-Data Mendelian Randomization: Some Cautionary Tales for Practice

This website provides full documentation of the code used for our paper, and step-by-step guides on how to reproduce every figure and result. For the curious, it was generated using [`pkgdown`](https://pkgdown.r-lib.org). 

The R-package `ACEBounds` includes every bit of code needed to reproduce all figures and results included in our paper. Since the main purpose is to ensure the reproducibility of figures and results from this specific paper, it has not been thoroughly tested in other settings. The code has not been optimized for performance, and was mainly written and documented for internal use only. That being said, many parts of this can be directly applied to other data sets, or reused in different settings. 

You can install this package using `remotes::install_github("rmtrane/ACEBounds-package")`. 

## Contents

* [Get started](articles/ACEBounds.html) is a brief introduction to this package, and how to find bounds using it.
* [Reference](reference/index.html) gives a list with links to the documentation of all functions included.
* Under [Articles](articles/index.html) you will find a set of documents that show how results and figures were created. Every document provides the seed used in order to make the work 100% reproducible. In particular, referencing our paper, Figure 1a is created [here](articles/bounds_from_bivaraite.html), Figures 1b, 2 and eFigure 1 are [here](articles/bounds_from_trivariate.html), all figures and results relating to real-world data examples are created [here](articles/example_analysis.html), and eFigure 2, 3, 4, 5, and 6 are created [here](articles/multiple_IVs.html). 

<!-- # Recap of Paper -->

<!-- ## Introduction -->

<!-- Non-parametric bounds of the Average Causal Effect (ACE) are intriguing for several reasons. Getting bounds on the ACE with no further assumptions other than what is embedded in the IV model is very appealing in particular as such assumptions often limit the structure of unmeasured confounders. By definition, assumptions about unmeasured confounders cannot be checked, and it is therefore desirable to avoid such.  -->

<!-- We will see how we can find nonparametric bounds in different practical settings, and how they unfortunately often lead to rather results from which a disappointing amount of insights can be gained.  -->

<!-- ## Motivation -->

<!-- Many have considered this approach in the past. @swanson_partial_2018 provide a nice overview of different bounds derived from different sets of assumptions. Arguably the weakest set of assumptions result in what is known as the Balke-Pearl bounds, first presented in @balke_nonparametric_1993.  -->

<!-- The same set of bounds can be obtained using a geometric approach as presented by @ramsahai_causal_2012. We will rely on this work as it provides a very general approach to finding bounds. This allows us to obtain bounds in a setting where we do not have observations of $(X,Y,Z)$, but rather observations of $(X,Z)$ and $(Y,Z)$ from two different data sources. (We will refer to the former as the one-sample setting, and the latter as the two-sample setting.) This is relevant today in many mendelian randomization (MR) analyses that have a natural desire to take advantage of the large databases readily available. In that vein, it is also of interest to further consider bounds obtained using IVs with three levels. Outside of @ramsahai_causal_2012, most work has been done using binary IVs in the one-sample setting. -->

<!-- ## Width of Two-Sample Bounds -->

<!-- One nice result for bounds obtained from one-sample data tells us that the width will never exceed $1$. This is important since bounds with width greater than $1$ will always include $0$, the null effect, which means direction of the ATE cannot be determined. Unfortunately, two-sample bounds can be as large as $2$. Particularly, for two-sample MR studies, most bounds are in fact close to or exceeding $1$.  -->

<!-- ## Improving Bounds from Two-Sample Data -->

<!-- Since relatively large databases with two-sample data are already available, it seems worthwhile to explore if we can utilize these data in any way to improve the bounds we obtain. We considered two ways of doing so. -->

<!-- ### Multiple IVs -->

<!-- The simplest way of utilizing multiple IVs is by simply taking intersections of the individual intervals. We will see that in most scenarios, the width of an intersection interval is mainly driven by the strongest IV. In fact, if monotonicity is assumed, it can be shown that the lower and upper bounds are monotonically increasing and decreasing, respectively, as a function of the strength of the IV, all else being equal. This means that the intersection will be exactly the bounds of the strongest IV. We show through simulations that even when all else is not equal, the gain in the width of the intersection is miniscule compared to the best individual bounds. -->

<!-- ### Possible One-Sample Distributions -->

<!-- Since we know that the bounds obtained from one-sample data will always have length less than $1$, and generally be narrower than the two-sample bounds, one could ask what distributions of $(X,Y|Z)$ would be possible given the known distributions of $(X|Z)$, $(Y|Z)$, and assuming the IV model holds. Doing so, one can arrive at what can be thought of as a posterior distribution of the one-sample bounds. This enables us to draw a few different conclusions depending on the specific scenario: -->

<!-- * a one-sample study provides no further insights over the two-sample bounds -->
<!-- * a one-sample study might be very likely to tell us the direction of the effect -->
<!-- * a one-sample study might be very unlikely to tell us the direction of the effect -->


<!-- ## Results/Conclusions -->

<!-- * Bounds based on two-sample data are not very useful -- we need very, very strong IVs to be guaranteed any insights. -->
<!-- * Even when utilizing multiple IVs, two-sample data will in most cases (in our experience) not provide enough information to be useful. -->
<!-- * It seems the best use of two-sample data is to get a sense of what one might be able to get from a one-sample study design. This could be used to decide whether or not pursuing such data for a bound based analysis is worth the time. -->


<!-- ## References -->
