---
output: pdf_document
---

\begin{flushright}
`r Sys.Date()`
\end{flushright}

Dear Editors,

\vspace{12pt}

I would like to submit the manuscript (co-authored with Dr. Hyunseung Kang) titled "Nonparametric Bounds in Two-Sample Summary-Data Mendelian Randomization: Some Cautionary Tales for Practice" for consideration for publication in Epidemiology. The manuscript considers the use of nonparametric bounds of the average treatment effect in two-sample Mendelian randomization studies, specifically addressing (1) the loss of information that occurs as compared to one-sample bounds, and (2) the usefulness of these bounds in practice. We are also attaching supplementary materials to be made available online if the manuscript were to be accepted. The supplementary materials contains (i) details on the process of deriving nonparametric bounds, (ii) specific details on the model underlying our simulations, (iii) proof of the main theorem of our work, and (iv) extended results from both simulations studies and analyses of real world data. 

\vspace{12pt}

Thank you for your consideration. 

\vspace{24pt}

Sincerely, 

\vspace{24pt}

Ralph Møller Trane \newline
Department of Statistics \newline
University of Wisconsin-Madison \newline
1300 University Avenue \newline
Madison, WI 53706
